POST http://localhost:3333/users
Content-Type: application/json
 
{
  "name": "Teste",
  "email": "hugoxvida@gmail.com",
  "password": "romerito"
}

###


POST http://localhost:3333/sessions/password
Content-Type: application/json
 
{
  "email": "hugo@acmeclerk.com",
  "password": "romerito1"
}

###

GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMDBjMDRiNC01ODQ3LTRjZTctOWExNi0xZDI2NWYyMzhlN2MiLCJpYXQiOjE3NDE4MjU3ODQsImV4cCI6MTc0MjQzMDU4NH0.lR4viIi7PYb3OMoM1e1S9NPnsHHy7BiqKmGELF89FKM
 

###


GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODk0MmQyYi1iMmNhLTQyNzItODg5Ny1kMDgyZTBhYzJhYjAiLCJpYXQiOjE3NDE4OTcyMjIsImV4cCI6MTc0MjUwMjAyMn0.Wyaf61qMlh3uc2gA7AM_JyyBrTmkjp-Ckeu4OA8Qs20
 

### Teste de autenticação com Google OAuth
POST http://localhost:3333/sessions/google
Content-Type: application/json

{
  "code": "4/0AQSTgQGPsgqDN05cvb5cgSYWTYUe9HMzPbkn0Ia_bJtJVZgYnQagboDoFzjNLJ72MRNyfQ"
}


### Teste de autenticação com Google OAuth
POST http://localhost:3333/organizations/equipe-ea/units/usf/invites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjA0ODIxZS0yNDk5LTQyYWYtYmY2ZS02NzVhMjMyZGY2NWUiLCJpYXQiOjE3NDIzMjEwMTEsImV4cCI6MTc0MjkyNTgxMX0.2Hj9kk9E_gDlBeQxFo8xpAF-1ORaTLTEoQ11lx2kjx4

{
  "email": "stuart@gmail.com",
  "role": "CLERK"
}

### Obter URL de autenticação do Google
GET http://localhost:3333/auth/google/url

###


GET http://localhost:3333/organizations/equipe-ea/units
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjA0ODIxZS0yNDk5LTQyYWYtYmY2ZS02NzVhMjMyZGY2NWUiLCJpYXQiOjE3NDIzMjEwMTEsImV4cCI6MTc0MjkyNTgxMX0.2Hj9kk9E_gDlBeQxFo8xpAF-1ORaTLTEoQ11lx2kjx4



###


GET http://localhost:3333/organizations/usf/membership
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MDMzN2U4MC0yZjhjLTQzNzItYjQyZC1kOTI5MGVkNDkwNTQiLCJpYXQiOjE3NDIzOTQyNzYsImV4cCI6MTc0Mjk5OTA3Nn0.1JEqjLsU4h9NwhH1eeQPaTwVY74o5UvXd-hXe9ANH3c
'


###


POST http://localhost:3333/invites/cb1dc80b-e4af-48f7-9e77-0f98cbd5bbc3/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTk1YzYxMC1lYTJiLTRhZTMtYmE4NS1mMjI2OGI2ZWZmOTAiLCJpYXQiOjE3NDIzOTQ4NTUsImV4cCI6MTc0Mjk5OTY1NX0.X2RliSz5NFb4s52Tj0Zg-lEgvlFgc-MoMq13UFOf1-A